services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ts_user -d ticks"]
      interval: 10s
      retries: 5
    environment:
      POSTGRES_USER: ts_user
      POSTGRES_PASSWORD: ts_pass
      POSTGRES_DB: ticks
    volumes:
      - timescale_data:/var/lib/postgresql/data
  
    ports: ["5432:5432"]

  listener:
    build: ../websocket-listener
    env_file:
      - ../websocket-listener/.env
    depends_on:
      - redis

  consumer:
    build: ../redis-consumer
    environment:
      POSTGRES_USER: ts_user
      POSTGRES_PASSWORD: ts_pass
      POSTGRES_DB: ticks
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  timescale_data:        
  