global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'listener'
    static_configs:
      - targets: ['listener:8000']

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8001']
