- hosts: all
  become: true
  tasks:
    - name: Install dependencies
      yum:
        name:
          - curl
          - unzip
        state: present

    - name: Install K3s
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash


    - name: Add Bitnami repo
      become: true
      shell: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Update Helm repos
      become: true
      shell: helm repo update

    - name: Install Redis
      become: true
      shell: helm install redis bitnami/redis --set auth.enabled=false

    - name: Install TimescaleDB
      become: true
      shell: helm install timescaledb bitnami/postgresql --set postgresqlDatabase=timescale
